### ISSUE TITLE
Update status bar footer to show breadcrumbs

### ISSUE THREAD

**Issue by raniceyue** [AY1920S2-CS2103T-F09-4/main#164]
Currently the status bar at the bottom shows the location at which volant's files are saved, which is not very useful. 

We should convert it to breadcrumbs such that it will be able to show users where they are in volant, e.g `Bali 2020 > ITINERARY`, `HOME`, `Grad Trip 2020` etc.

**Comment by zsoh97** [comment]
done in #223
