### ISSUE TITLE
Bug: Fix definition of duplicate trip

### ISSUE THREAD

**Issue by raniceyue** [AY1920S2-CS2103T-F09-4/main#215]
**NOTES FOR IMPLEMENTATION**

2 trips should only be considered duplicates if they have the same name.

Trips with the same date are not duplicates but are trips with clashing dates. Trips with clashing dates should return exceptions.

Location should not be considered in the equality between 2 trips at all. 

Please see #194 for details on how to replicate errors

**Comment by zsoh97** [comment]
fixed in #223
