### ISSUE TITLE
Implement model for date and time for journal entry 

### ISSUE THREAD

**Issue by raniceyue** [AY1920S2-CS2103T-F09-4/main#91]

**Comment by raniceyue** [comment]
I think for journal entries we should implement such that the date and time will be automatically initialized to the date and time at which the user is writing the journal entry.

**Comment by mikhailfaiz** [comment]
We have not implemented date and time of creation because it's only going to be used for sorting, which is only to be implemented in v1.3.

**Comment by grrrrnt** [comment]
Implemented in #105 and #106 (using user-input date and time)
